### PR TITLE
Project updates for spring 24

### PR DESCRIPTION
**Pull request by a-tk**
@boiseamit @jyhhawyeh 

I discussed with Amit during last semester some minor changes to the projects for CS321. Here they are summarized: 

1. Add unit tests to project 1. This is intended to help students understand what test driven development is, and become familiar with how Junit is used in an actual project. This will help them have a template for Project 2 as well. Since the unit test class is called CacheTest, the class the students should implement should be renamed CacheExperiment.
2. Rename HashTableTest to HashTableExperiment to prevent confusing students about its purpose. 

If you approve, the following still needs to be done:

- [ ] Modify google doc for Project 1 to include description of the tests
- [ ] Modify google doc for Project 1 to reflect the updated name CacheExperiment
- [ ] Modify google doc for Project 3 to reflect the updated name HashTableExperiment

### CODE REVIEW

**Comment by a-tk** [comment]
For some reason github prevents me from requesting you to review @jyhhawyeh.

**Comment by jyhhawyeh** [comment]
Hello Andre, thanks for the updates. I will go over the changes. If I have
equations, I will ask you for help.

Jyh-haw

**Comment by a-tk** [comment]
Dr. Yeh didn't have an issue with me merging this in, and I'm assigning the project tomorrow, so I'll merge it.

**Comment by boiseamit** [comment]
Sure. I had reviewed it before but for some reason I wasn't getting an option to merge it at that time?

**Pull request merged**
